site_name: Coding for Planners & Engineers
theme:
  name: material
  icon:
    logo: material/map-legend
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
nav:
  - Home: index.md
  - Introduction:
      - Python: Python/README.md
      - SQL: SQL/README.md
      - R: R/README.md
  - Python Basics:
      - 101: Python/examples/basics/python_101.ipynb
      - 202: Python/examples/basics/python_202.ipynb
  - Python Libraries:
      - pandas: Python/examples/libraries/pandas.ipynb
      - geopandas: Python/examples/libraries/geopandas.ipynb
      - plotly: Python/examples/libraries/plotly.ipynb
  - Databases:
      - .env file: Python/examples/databases/dotenv.ipynb
      - psycopg2: Python/examples/databases/psycopg2.ipynb
      - sqlalchemy: Python/examples/databases/sqlalchemy.ipynb
  - R Basics:
      - Exercise: R/examples/exercise.md
      - Exercise Answers: R/examples/exercise_answers.md

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
